version: "3"

services:

  account:
    container_name: cinschool.account
    build:
      context: ./client
      args:
        - PROJECT=account
    networks: [default]
    ports: [7010:4200]
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes:
      - ./client/:/app

  portal:
    container_name: cinschool.portal
    build:
      context: ./client
      args:
        - PROJECT=portal
    networks: [default]
    ports: [7011:4200]
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes:
      - ./client/:/app

  admin:
    container_name: cinschool.admin
    build:
      context: ./client
      args:
        - PROJECT=admin
    networks: [default]
    ports: [7012:4200]
    restart: unless-stopped
    stop_signal: SIGKILL
    volumes:
      - ./client/:/app

  server:
    container_name: cinschool.server
    build:
      context: ./server
    networks: [default]
    ports: [7013:8080]
    restart: unless-stopped
    volumes:
      - ./server/:/src

  frontend:
    container_name: cinschool.frontend
    image: nginx:latest
    networks: [default]
    ports: [7000:8080]
    restart: always
    volumes:
      - ./reverse_proxy_nginx.conf:/etc/nginx/conf.d/default.conf
   
volumes:
  cinschool-db:
    driver: local
